title: Marco Roganovic
description: Full-Stack Developer and aspiring designer

url: ""
baseurl: ""
paginate_path: "blog/page/:num"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: http://marcoroganovic.github.io/#about-me
 - title: Contact
   url: http://marcoroganovic.github.io/#contact

social:
   github: marcoroganovic
   twitter: marcoroganovic
   email: marcoroganovic@gmail.com

google_analytics: "UA-58263416-1"
